id: ACCD887C8
title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
  Practice that Unites the Oral, Treasure and Visionary Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:44:46.312937
  last_modified_at: 2022-02-28 22:44:46.312944
